[caprice]Complete the install procedure (now you must install caprice in order to launch it)

diff --git a/CapIHM/configure b/CapIHM/configure
--- a/CapIHM/configure
+++ b/CapIHM/configure
@@ -700,6 +700,9 @@ ac_ct_CC
 CCDEPMODE
 am__fastdepCC_TRUE
 am__fastdepCC_FALSE
+regex_cmd
+RELEASE_TRUE
+RELEASE_FALSE
 WX_CONFIG_PATH
 WX_CPPFLAGS
 WX_CFLAGS
@@ -710,8 +713,6 @@ WX_LIBS
 WX_LIBS_STATIC
 WX_VERSION
 WX_RESCOMP
-RELEASE_TRUE
-RELEASE_FALSE
 SOUNDLIB
 AYLET_TRUE
 AYLET_FALSE
@@ -1316,15 +1317,16 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+--with-stsound          use St Sound backend default=yes
+--with-aylet		use Aylet backend default=no
+--with-ayemu		use LibAYEmul default=no
+--with-lib765		use lib765 backend associate with libdsk for fdc emulationdefault=yes
+--with-wxwidget	use wxWidget as a gui default=yes
   --with-wxdir=PATH       Use uninstalled version of wxWidgets in PATH
   --with-wx-config=CONFIG wx-config script to use (optional)
   --with-wx-prefix=PREFIX Prefix where wxWidgets is installed (optional)
   --with-wx-exec-prefix=PREFIX
                           Exec prefix where wxWidgets is installed (optional)
---with-stsound          use St Sound backend default=yes
---with-aylet		use Aylet backend default=no
---with-ayemu		use LibAYEmul default=no
---with-lib765		use lib765 backend associate with libdsk for fdc emulationdefault=yes
   --with-sdl-prefix=PFX   Prefix where SDL is installed (optional)
   --with-sdl-exec-prefix=PFX Exec prefix where SDL is installed (optional)
 
@@ -6820,9 +6822,140 @@ _ACEOF
   esac
 
 
+
+for ac_prog in sed
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_regex_cmd+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$regex_cmd"; then
+  ac_cv_prog_regex_cmd="$regex_cmd" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_regex_cmd="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+regex_cmd=$ac_cv_prog_regex_cmd
+if test -n "$regex_cmd"; then
+  { echo "$as_me:$LINENO: result: $regex_cmd" >&5
+echo "${ECHO_T}$regex_cmd" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  test -n "$regex_cmd" && break
+done
+
+if test x$regex_cmd = "x" ; then
+	    { { echo "$as_me:$LINENO: error: sed is required to build the data files." >&5
+echo "$as_me: error: sed is required to build the data files." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 #AM_PROG_CC_C_O
 
 
+#ARGS
+
+
+# Check whether --with-stsound was given.
+if test "${with_stsound+set}" = set; then
+  withval=$with_stsound; with_stsound=no
+else
+  with_stsound=yes
+fi
+
+
+
+
+# Check whether --with-aylet was given.
+if test "${with_aylet+set}" = set; then
+  withval=$with_aylet; with_aylet=yes
+else
+  with_aylet=no
+fi
+
+
+
+# Check whether --with-ayemu was given.
+if test "${with_ayemu+set}" = set; then
+  withval=$with_ayemu; with_ayemu=yes
+else
+  with_ayemu=no
+fi
+
+
+
+
+# Check whether --with-dsk was given.
+if test "${with_dsk+set}" = set; then
+  withval=$with_dsk; with_lib765=no
+else
+  with_lib765=yes
+fi
+
+
+
+# Check whether --with-wxWidget was given.
+if test "${with_wxWidget+set}" = set; then
+  withval=$with_wxWidget; with_wxwidget=no
+else
+  with_wxwidget=yes
+fi
+
+
+{ echo "$as_me:$LINENO: checking for debugging environment" >&5
+echo $ECHO_N "checking for debugging environment... $ECHO_C" >&6; }
+# Check whether --enable-debug was given.
+if test "${enable_debug+set}" = set; then
+  enableval=$enable_debug; enable_debug=no
+else
+  enable_debug=yes
+fi
+
+
+
+
+if test "$enable_debug" = yes ; then
+	CXXFLAGS="-O0 -Wall -g -DDEBUG"
+	CFLAGS="-O0 -Wall  -g -DDEBUG"
+fi
+
+ if test ! "enable_debug" = "yes"; then
+  RELEASE_TRUE=
+  RELEASE_FALSE='#'
+else
+  RELEASE_TRUE='#'
+  RELEASE_FALSE=
+fi
+
+
+{ echo "$as_me:$LINENO: result:  $enable_debug " >&5
+echo "${ECHO_T} $enable_debug " >&6; }
+
+
+
+# GUI
+if test "$with_wxwidget" = "yes" ; then
 
 
 
@@ -6837,7 +6970,8 @@ _ACEOF
 
 
 
-#IHM
+
+
 
 
 # Check whether --with-wxdir was given.
@@ -6869,7 +7003,7 @@ else
 fi
 
 
-reqwx=2.4.0
+	reqwx=2.4.0
 
     if test x${WX_CONFIG_NAME+set} != xset ; then
      WX_CONFIG_NAME=wx-config
@@ -7102,7 +7236,7 @@ echo "${ECHO_T}no (version $WX_VERSION is not new enough)" >&6; }
 
 
 
-if test "$wxWin" != 1; then
+	if test "$wxWin" != 1; then
 	{ { echo "$as_me:$LINENO: error:
 		wxWidgets must be installed on your system.
 
@@ -7122,77 +7256,8 @@ echo "$as_me: error:
 		wxWidgets version is $reqwx or above.
 		" >&2;}
    { (exit 1); exit 1; }; }
+	fi
 fi
-
-
-
-#ARGS
-
-
-# Check whether --with-stsound was given.
-if test "${with_stsound+set}" = set; then
-  withval=$with_stsound; with_stsound=no
-else
-  with_stsound=yes
-fi
-
-
-
-
-# Check whether --with-aylet was given.
-if test "${with_aylet+set}" = set; then
-  withval=$with_aylet; with_aylet=yes
-else
-  with_aylet=no
-fi
-
-
-
-# Check whether --with-ayemu was given.
-if test "${with_ayemu+set}" = set; then
-  withval=$with_ayemu; with_ayemu=yes
-else
-  with_ayemu=no
-fi
-
-
-
-
-# Check whether --with-dsk was given.
-if test "${with_dsk+set}" = set; then
-  withval=$with_dsk; with_lib765=no
-else
-  with_lib765=yes
-fi
-
-
-
-{ echo "$as_me:$LINENO: checking for debugging environment" >&5
-echo $ECHO_N "checking for debugging environment... $ECHO_C" >&6; }
-# Check whether --enable-debug was given.
-if test "${enable_debug+set}" = set; then
-  enableval=$enable_debug; enable_debug=no
-else
-  enable_debug=yes
-fi
-
-
-if test "$enable_debug" = yes ; then
-	CXXFLAGS="-O0 -Wall -g -DDEBUG"
-	CFLAGS="-O0 -Wall  -g -DDEBUG"
-fi
-
- if test ! "enable_debug" = "yes"; then
-  RELEASE_TRUE=
-  RELEASE_FALSE='#'
-else
-  RELEASE_TRUE='#'
-  RELEASE_FALSE=
-fi
-
-
-{ echo "$as_me:$LINENO: result:  $enable_debug " >&5
-echo "${ECHO_T} $enable_debug " >&6; }
 
 
 # Sound
@@ -8905,6 +8970,9 @@ ac_ct_CC!$ac_ct_CC$ac_delim
 CCDEPMODE!$CCDEPMODE$ac_delim
 am__fastdepCC_TRUE!$am__fastdepCC_TRUE$ac_delim
 am__fastdepCC_FALSE!$am__fastdepCC_FALSE$ac_delim
+regex_cmd!$regex_cmd$ac_delim
+RELEASE_TRUE!$RELEASE_TRUE$ac_delim
+RELEASE_FALSE!$RELEASE_FALSE$ac_delim
 WX_CONFIG_PATH!$WX_CONFIG_PATH$ac_delim
 WX_CPPFLAGS!$WX_CPPFLAGS$ac_delim
 WX_CFLAGS!$WX_CFLAGS$ac_delim
@@ -8913,9 +8981,6 @@ WX_CFLAGS_ONLY!$WX_CFLAGS_ONLY$ac_delim
 WX_CXXFLAGS_ONLY!$WX_CXXFLAGS_ONLY$ac_delim
 WX_LIBS!$WX_LIBS$ac_delim
 WX_LIBS_STATIC!$WX_LIBS_STATIC$ac_delim
-WX_VERSION!$WX_VERSION$ac_delim
-WX_RESCOMP!$WX_RESCOMP$ac_delim
-RELEASE_TRUE!$RELEASE_TRUE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -8957,7 +9022,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
-RELEASE_FALSE!$RELEASE_FALSE$ac_delim
+WX_VERSION!$WX_VERSION$ac_delim
+WX_RESCOMP!$WX_RESCOMP$ac_delim
 SOUNDLIB!$SOUNDLIB$ac_delim
 AYLET_TRUE!$AYLET_TRUE$ac_delim
 AYLET_FALSE!$AYLET_FALSE$ac_delim
@@ -8968,7 +9034,7 @@ SDL_LIBS!$SDL_LIBS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 9; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 10; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
